version: 0.2
env:
  secrets-manager:
    LOGIN: prod/sonar:sonartoken
    HOST: prod/sonar:HOST
    Organization: prod/sonar:Organization
    Project: prod/sonar:Project
phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - npm install -g typescript
      - npm install
      - npm install sonarqube-scanner
  pre_build:
    commands:
      - sonar.login=$LOGIN
      - sonar.host.url=$HOST
      - sonar.projectKey=$Project
      - sonar.organization=$Organization
  build:
    commands:
